# Generated by Django 4.1 on 2022-12-03 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_rename_pub_data_question_pub_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="QuestionText",
            new_name="question_text",
        ),
    ]
